# Generated by Django 5.0.7 on 2024-07-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recentreads', '0002_alter_book_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
