# Generated by Django 5.0.7 on 2024-07-17 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recentreads', '0003_alter_book_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
