# Generated by Django 5.0.7 on 2024-07-17 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recentreads', '0004_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.CharField(max_length=200),
        ),
    ]
