# Generated by Django 5.0.7 on 2024-07-17 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recentreads', '0005_alter_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='goodreads_link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
