# Generated by Django 5.0.7 on 2024-07-17 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recentreads', '0007_alter_author_goodreads_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='goodreads_link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
