# Generated by Django 5.0.7 on 2024-07-17 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recentreads', '0009_alter_book_goodreads_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='review',
        ),
    ]
